#!/bin/sh

#teclado 
setxkbmap latam

#autostart
sxhkd &
dunst &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf &

feh --bg-scale ~/Imágenes/wallpaper.jpg &

# Indicadores
nm-applet &
blueman-applet &
volumeicon &

#caracteristicas
bspc monitor -d 1 2 3 4 5 6
bspc config border_width 2
bspc config window_gap 10

#colores
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
